local L = LibStub("AceLocale-3.0"):NewLocale("Yatabar","enUS",true)
if not L then return end
	L["Totem with popup buttons"] = "Totem bar with popup buttons"
	L["new spell learned"] = "You have learned a new spell, check option menu"
	L["Set the order of the element"] = "Set the order of the element:"
	L["Totem configuration"] = "Totem configuration"
	L["Click to change order"] = "Click to change order"
	L["Set Order"] = "Set order"
	L["AIR"] = "AIR"
	L["EARTH"] = "Earth"
	L["WATER"] = "Water"
	L["FIRE"] = "Fire"
	L["show"] = "show"
	L["Position "] = "Position "
	L["no more spell to switch"] = "No more spell to switch"
	L["function not available during combat"] = "Function not available during combat"
	L["Set the orientation of the bar."] = "Set the orientation of the bar." 
	L["Left Click|r to open configuration"] = "Left Click|r to open configuration"
	L["Right Click|r to lock/unlock bar"] = "Right Click|r to lock/unlock bar"
	L["Middle Click|r to show/hide the bar"] = "Middle Click|r to show/hide the bar"
	L["Totem not active"] = "Totem is not active"
	L["Shift-key"] = "Shift-key"
	L["Alt-key"] = "Alt-key"
	L["Control-key"] = "Control-key"
	L["no key"]  = "no key"
	L["buttonsize"] = "Button size"
	L["buttonsize desc"] = "Set the size of the buttons"
	L["Hide timer bars"] = "Hide totem timer"
	L["Hide timer bars desc"] = "Hide the totem timer bars"
	L["Set key binding"] = "Set key binding"
	L["Set the key binding desc"] = "Bind a key for that element"
	L["Hide the bar"] = "Hide the bar"
	L["Set popup key"] = "Set popup key"
	L["Set popup key desc"] = "Set the key to show the popup buttons"
	L["Hide minimap icon"] =  "Hide minimap icon"
	L["Hide minimap icon desc"] =  "Hide the minimap icon"
	L["key already bind"] = "key was binded to: "
	L["Select set"] = "Select set"
	L["Select set desc"] = "Select the totem set"
	L["Save set"] = "Save set"
	L["Create new set"] = "Create new set"
	L["Delete set"] = "Delete set"
	L["Profile cannot be changed in combat"] = "Profile cannot be changed in combat"
	L["Cannot delete profile"] = "Cannot delete profile"
	L["Delete profile - "] = "Delete profile - "

	L["Hides the default mainbar"] = true 
	L["Button Lock"] = true
	L["Lock the buttons"] = true 
	L["Lock the bar"] = "Lock the bar"
	L["Lock/Unlock the bar"] = "Lock/Unlock the bar"
	L["Scale buttons"] = true 
	L["Scale the buttons"] = true 
	L["Invert popup direction"] = true 
	L["Vertical bar direction"] = true 
	L["Tooltip configuration"] = true 
	L["Show Tooltip"] = true 
	L["Out of combat only"] = true 
	L["Yatabar configuration"] = true 
	L["Popup Button Scale"] = true 
	L["Scale the popup buttons"] = true 
	L["Button Style"] = true 
	L["Show short tooltip"] = true 
	L["Orientation"] = true 
	L["Horizontal, Grow Up"] = true 
	L["Horizontal, Grow Down"] = true
	L["Vertical, Grow Right"] = true 
	L["Vertical, Grow Left"] = true 
	L["Add popup button"] = true 
	L["Add a new popup button"] = true 
	L["New row"] = true 
	L["Add a new row"] = true 
	L["New main button"] = true 
	L["Delete main button"] = true	
	L["Delete the last main button"] = true
	L["Add a new main button"] = true 
	L["Main button "] = true
	L["Options for this main button"] = true
	L["Row "] = true 
	L["Options for this row"] = true 
	L["Delete row"] = true 
	L["Delete last row"] = true 
	L["Delete popup button"] = true 
	L["Delete the last popup button"] = true 
	L["Tooltip"] = true 
	L["Enable/disable the tooltips"] = true 
	L["Padding"] = true 
	L["Set the padding of the buttons"] = true 
	L["Change main button-ID"] = true 
	L["Change the ID of this mainbutton"] = true 
	L["Bar "] = true 
	L["Options for the bar"] = true 
	L["Add Bar"] = true 
	L["Add a new bar"] = true 
	L["Delete Bar"] = true 
	L["Delete the last bar"] = true 
	L["Popup button "] = true 
	L["Options for the popup button"] = true 
	L["Change the ID of this popup button"] = true 
	L["Change ID of popup button: "] = true 
	L["Show all buttonids"] = true 
	L["Shows all buttons with their ids"] = true
	L["no more popup button to delete"] = true
	
