local L = LibStub("AceLocale-3.0"):NewLocale("Yatabar","enUS",true)
if not L then return end

	L["Hide mainbar"] = true 	
	L["Hides the default mainbar"] = true 
	L["Button Lock"] = true
	L["Lock the buttons"] = true 
	L["Lock the bar"] = true 
	L["Scale buttons"] = true 
	L["Scale the buttons"] = true 
	L["Invert popup direction"] = true 
	L["Vertical bar direction"] = true 
	L["Tooltip configuration"] = true 
	L["Show Tooltip"] = true 
	L["Out of combat only"] = true 
	L["Yatabar configuration"] = true 
	L["Popup Button Scale"] = true 
	L["Scale the popup buttons"] = true 
	L["Button Style"] = true 
	L["Show short tooltip"] = true 
	L["Orientation"] = true 
	L["Set the orientation of the bar."] = "Set the orientation of the bar." 
	L["Horizontal, Grow Up"] = true 
	L["Horizontal, Grow Down"] = true
	L["Vertical, Grow Right"] = true 
	L["Vertical, Grow Left"] = true 
	L["Add popup button"] = true 
	L["Add a new popup button"] = true 
	L["New row"] = true 
	L["Add a new row"] = true 
	L["New main button"] = true 
	L["Delete main button"] = true	
	L["Delete the last main button"] = true
	L["Add a new main button"] = true 
	L["Main button "] = true
	L["Options for this main button"] = true
	L["Row "] = true 
	L["Options for this row"] = true 
	L["Delete row"] = true 
	L["Delete last row"] = true 
	L["Delete popup button"] = true 
	L["Delete the last popup button"] = true 
	L["Tooltip"] = true 
	L["Enable/disable the tooltips"] = true 
	L["Padding"] = true 
	L["Set the padding of the buttons"] = true 
	L["Change main button-ID"] = true 
	L["Change the ID of this mainbutton"] = true 
	L["Bar "] = true 
	L["Options for the bar"] = true 
	L["Add Bar"] = true 
	L["Add a new bar"] = true 
	L["Delete Bar"] = true 
	L["Delete the last bar"] = true 
	L["Popup button "] = true 
	L["Options for the popup button"] = true 
	L["Change the ID of this popup button"] = true 
	L["Change ID of popup button: "] = true 
	L["Show all buttonids"] = true 
	L["Shows all buttons with their ids"] = true
	L["no more popup button to delete"] = true
	L["Left Click|r to open configuration"] = true
	L["Right Click|r to lock/unlock bar"] = "Right Click|r to lock/unlock bar"
