if select(2, UnitClass('player')) ~= "SHAMAN" then
	return
end
local L = LibStub("AceLocale-3.0"):NewLocale("Yata", "zhCN", true)
if not L then return end

L["Advanced"] = "高级" -- Needs review
L["AdvancedDesc"] = "高级选项" -- Needs review
L["AdvancedHeader"] = "高级选项（风险自负）" -- Needs review
L["Alpha"] = "透明度" -- Needs review
L["AlphaDesc"] = "配置图腾条的透明度。设置为1时为完全可见，设置为0时为完全不可见。" -- Needs review
L["Appearance"] = "外观" -- Needs review
L["AppearanceDesc"] = "配置条的外观" -- Needs review
L["AssignToCall"] = "分配图腾" -- Needs review
L["AssignToCallDesc"] = "当左键点击时按住这个按钮将分配已选择的图腾到当前的多重施放法术。如果这个图腾已经属于那个法术将会移除这个图腾。" -- Needs review
L["Bindings"] = "行为" -- Needs review
L["BindingsDesc"] = "配置当点击按钮时的行为动作" -- Needs review
L["BrokerLock"] = "解锁/锁定条" -- Needs review
L["BrokerOptions"] = "右键点击打开选项" -- Needs review
L["CastOnly"] = "仅施放" -- Needs review
L["CastOnlyDesc"] = "当左键点击时按住这个键将施放已选择的法术, 但是不会改变按钮的顺序" -- Needs review
L["DeleteSetName"] = "输入要删除的组合名字" -- Needs review
L["EnableAdvanced"] = "启用高级功能？" -- Needs review
L["EnableAdvancedDesc"] = "启用高级功能" -- Needs review
L["EnableAutoSwap"] = "自动切换按钮" -- Needs review
L["EnableAutoSwapDesc"] = "当选择这个后，施放一个法术将把此法术带到前面" -- Needs review
L["EnableCallSwap"] = "自动切换召唤法术" -- Needs review
L["EnableCallSwapDesc"] = "当这个被选中后，施放一个多重施法法术（如元素的召唤）将把那个分组的所有图腾带到前面" -- Needs review
L["EnableMacro"] = "启用宏" -- Needs review
L["EnableMacroDesc"] = "Enables the creation of the Yata totem stomping macro" -- Requires localization
L["EnableTimers"] = "启用计时器" -- Needs review
L["EnableTimersDesc"] = "当选中后，将显示图腾的计时器和冷却" -- Needs review
L["Gap"] = "按钮间距" -- Needs review
L["GapDesc"] = "修改按钮之间的间距" -- Needs review
L["HD"] = "水平条, 向下展开" -- Needs review
L["HU"] = "水平条, 向上展开" -- Needs review
L["HideBar"] = "隐藏 Yata 图腾条？" -- Needs review
L["HideBarDesc"] = "When this is set yata will continue to function (timer bars and keybindings will still work) but the totem bar will not be displayed" -- Requires localization
L["HideIndicators"] = "隐藏这个多重施法指示器？" -- Needs review
L["HideIndicatorsDesc"] = "When this is set the indicator blocks will not be displayed on totems.  You will still be able to see which spells are in a multicast spell in the tooltip (if enabled) or by bringing the multicast spell to the front using the click binding" -- Requires localization
L["Lock"] = "锁定框体" -- Needs review
L["LockDesc"] = "反选这个来移动计时器条和图腾条" -- Needs review
L["Macro"] = "宏" -- Needs review
L["MacroDesc"] = "Configure the Yata totem stomping macro.  This macro will automatically update to always drop the visible totems in a sequence" -- Requires localization
L["MacroReset"] = "宏重置按钮" -- Needs review
L["MacroResetDesc"] = "Sets the button that will reset the cast sequence if the macro is clicked while the button is pressed" -- Requires localization
L["MultiTooltip"] = "添加图腾到提示信息？" -- Needs review
L["MultiTooltipDesc"] = "When checked, Yata will add the totems in a Multicast spell to the tooltip" -- Requires localization
L["Multicast"] = "多重施放法术（如元素的召唤）" -- Needs review
L["NewSetName"] = "输入组合的名字" -- Needs review
L["Orientation"] = "条布局" -- Needs review
L["OrientationDesc"] = "允许你选择条的方向和条打开的方向" -- Needs review
L["PopScale"] = "弹出缩放" -- Needs review
L["PopScaleDesc"] = "修改从条弹出的法术大小" -- Needs review
L["Reset"] = "重置"
L["ResetDesc"] = "这个将删除你的配置文件并重置你的插件为默认" -- Needs review
L["Scale"] = "条缩放" -- Needs review
L["ScaleDesc"] = "修改条的缩放值" -- Needs review
L["ShowBlizzBar"] = "显示暴雪自带图腾条？" -- Needs review
L["ShowBlizzBarDesc"] = "当这个被设置时候Yata将不再隐藏暴雪自带的图腾条。你可以选择同时使用或使用上面的选项来隐藏Yata条。注意：如果你使用DOMINOS动作条插件这个将不会正常运行。需要重载插件。" -- Needs review
L["ShowCall"] = "将全部图腾带到前面" -- Needs review
L["ShowCallDesc"] = "当右键点击一个多重施放法术（如元素的召唤）时按住这个按钮将把那个分组的所有图腾带到前面" -- Needs review
L["ShowKeybind"] = "显示按键绑定？" -- Needs review
L["ShowKeybindDesc"] = "当选中后，按钮上将显示按键绑定" -- Needs review
L["Skin"] = "皮肤" -- Needs review
L["SkinDesc"] = "Yata 支持使用Button Facade来美化按钮. " -- Needs review
L["SpellCount"] = "可见法术数量" -- Needs review
L["SpellCountDesc"] = "修改总是可见的条的行（或列）的数量" -- Needs review
L["Spells"] = "所有按钮" -- Needs review
L["SwapButton"] = "带到前面" -- Needs review
L["SwapButtonDesc"] = "当左键点击时按住这个按钮将把已选择的图腾带到前面" -- Needs review
L["TBTT"] = "底部到顶部" -- Needs review
L["TLTR"] = "左边到右边" -- Needs review
L["TRTL"] = "右边到左边" -- Needs review
L["TTTB"] = "顶部到底部" -- Needs review
L["TimerBar"] = "计时条选项" -- Needs review
L["TimerBars"] = "计时条" -- Needs review
L["TimerBoth"] = "两者都" -- Needs review
L["TimerFont"] = "字体" -- Needs review
L["TimerFontDesc"] = "选择显示在计时条上文字的字体。Yata 支持 LibSharedMedia 库的自定义字体" -- Needs review
L["TimerFontSize"] = "文字大小" -- Needs review
L["TimerFontSizeDesc"] = "设置显示在计时条上文字的大小" -- Needs review
L["TimerGrowUp"] = "条向上增长？" -- Needs review
L["TimerGrowUpDesc"] = "当选中后，新的条将显示在锚点的上部。 当未选中后，新的条将显示在锚点的下面。" -- Needs review
L["TimerLength"] = "长度" -- Needs review
L["TimerLengthDesc"] = "设置计时条的长度" -- Needs review
L["TimerOrientation"] = "方向" -- Needs review
L["TimerOrientationDesc"] = "设置计时条的方向" -- Needs review
L["TimerScale"] = "缩放" -- Needs review
L["TimerScaleDesc"] = "设置计时条的缩放" -- Needs review
L["TimerSelf"] = "按钮" -- Needs review
L["TimerSpacing"] = "间距" -- Needs review
L["TimerSpacingDesc"] = "设置独立计时条之间的距离" -- Needs review
L["TimerStrata"] = "层级" -- Needs review
L["TimerStrataDesc"] = "设置条的层级。 高等级的层级意味着条将显示在所有其他UI元件的上面" -- Needs review
L["TimerTexture"] = "材质" -- Needs review
L["TimerTextureDesc"] = "Yata 使用 LibSharedMedia 库来设置计时条的材质." -- Needs review
L["TimerThickness"] = "厚度" -- Needs review
L["TimerThicknessDesc"] = "设置独立计时条的厚度" -- Needs review
L["TimerType"] = "类型" -- Needs review
L["TimerTypeDesc"] = "你可以在按钮中显示计时器或在外部的条中显示" -- Needs review
L["Timers"] = "计时器" -- Needs review
L["TimersDesc"] = "配置计时器" -- Needs review
L["Tooltip"] = "提示信息类型" -- Needs review
L["TooltipDesc"] = "选择当你鼠标悬停到按钮上时显示的鼠标提示的类型" -- Needs review
L["TooltipFull"] = "完整" -- Needs review
L["TooltipNone"] = "无" -- Needs review
L["TooltipShort"] = "短" -- Needs review
L["TotemSets"] = "图腾组合" -- Needs review
L["TotemSetsButton"] = "组合编辑器" -- Needs review
L["TotemSetsButtonDesc"] = "点击打开图腾组合编辑器" -- Needs review
L["TotemSetsDesc"] = "配置图腾组合" -- Needs review
L["VL"] = "垂直条，向左展开" -- Needs review
L["VR"] = "垂直条, 向右展开" -- Needs review
L["XDesc"] = "设置条的横向位置" -- Needs review
L["YDesc"] = "设置条的纵向位置" -- Needs review
